-- Run the Console between running initial entries 1 and 2
-- Initial inserts: update a range of games to show 1 tournament finished, and 1 ongoing
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 1;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 2;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 3;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 4;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 5;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 6;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 7;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 8;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 9;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 10;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 11;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 12;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 13;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 14;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 15;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 16;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 17;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 18;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 19;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 20;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 21;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 22;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 23;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 24;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 25;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 26;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 27;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 28;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 29;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 30;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 31;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 32;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 33;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 34;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 35;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 36;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 37;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 38;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 39;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 40;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 41;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 42;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 43;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 44;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 45;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 46;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 47;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 48;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 49;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 50;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 51;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 52;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 53;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 54;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 55;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 56;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 57;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 58;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 59;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 60;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 61;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 62;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 63;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 64;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 65;
UPDATE games SET (started, finished) = (TRUE, TRUE) WHERE id = 66;

-- Initial Insert: goals for completed polo league. Most give generic players.
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 88);
INSERT INTO goals (game_id, player_id) VALUES (10, 49);
INSERT INTO goals (game_id, player_id) VALUES (1, 62);
INSERT INTO goals (game_id, player_id) VALUES (1, 62);
INSERT INTO goals (game_id, player_id) VALUES (1, 62);
INSERT INTO goals (game_id, player_id) VALUES (1, 62);
INSERT INTO goals (game_id, player_id) VALUES (54, 49);
INSERT INTO goals (game_id, player_id) VALUES (54, 67);
INSERT INTO goals (game_id, player_id) VALUES (47, 49);
INSERT INTO goals (game_id, player_id) VALUES (47, 49);
INSERT INTO goals (game_id, player_id) VALUES (47, 49);
INSERT INTO goals (game_id, player_id) VALUES (47, 49);
INSERT INTO goals (game_id, player_id) VALUES (47, 49);
INSERT INTO goals (game_id, player_id) VALUES (47, 82);
INSERT INTO goals (game_id, player_id) VALUES (47, 82);
INSERT INTO goals (game_id, player_id) VALUES (3, 49);
INSERT INTO goals (game_id, player_id) VALUES (3, 49);
INSERT INTO goals (game_id, player_id) VALUES (3, 49);
INSERT INTO goals (game_id, player_id) VALUES (3, 55);
INSERT INTO goals (game_id, player_id) VALUES (3, 55);
INSERT INTO goals (game_id, player_id) VALUES (3, 55);
INSERT INTO goals (game_id, player_id) VALUES (3, 57);
INSERT INTO goals (game_id, player_id) VALUES (12, 49);
INSERT INTO goals (game_id, player_id) VALUES (12, 49);
INSERT INTO goals (game_id, player_id) VALUES (12, 72);
INSERT INTO goals (game_id, player_id) VALUES (6, 49);
INSERT INTO goals (game_id, player_id) VALUES (6, 49);
INSERT INTO goals (game_id, player_id) VALUES (6, 49);
INSERT INTO goals (game_id, player_id) VALUES (6, 49);
INSERT INTO goals (game_id, player_id) VALUES (6, 49);
INSERT INTO goals (game_id, player_id) VALUES (6, 67);
INSERT INTO goals (game_id, player_id) VALUES (6, 67);
INSERT INTO goals (game_id, player_id) VALUES (6, 67);
INSERT INTO goals (game_id, player_id) VALUES (6, 67);
INSERT INTO goals (game_id, player_id) VALUES (44, 49);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (44, 87);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 51);
INSERT INTO goals (game_id, player_id) VALUES (36, 57);
INSERT INTO goals (game_id, player_id) VALUES (16, 49);
INSERT INTO goals (game_id, player_id) VALUES (16, 49);
INSERT INTO goals (game_id, player_id) VALUES (16, 49);
INSERT INTO goals (game_id, player_id) VALUES (16, 49);
INSERT INTO goals (game_id, player_id) VALUES (16, 49);
INSERT INTO goals (game_id, player_id) VALUES (16, 49);
INSERT INTO goals (game_id, player_id) VALUES (16, 82);
INSERT INTO goals (game_id, player_id) VALUES (16, 82);
INSERT INTO goals (game_id, player_id) VALUES (8, 49);
INSERT INTO goals (game_id, player_id) VALUES (8, 49);
INSERT INTO goals (game_id, player_id) VALUES (8, 49);
INSERT INTO goals (game_id, player_id) VALUES (8, 62);
INSERT INTO goals (game_id, player_id) VALUES (8, 62);
INSERT INTO goals (game_id, player_id) VALUES (8, 62);
INSERT INTO goals (game_id, player_id) VALUES (8, 62);
INSERT INTO goals (game_id, player_id) VALUES (31, 49);
INSERT INTO goals (game_id, player_id) VALUES (31, 49);
INSERT INTO goals (game_id, player_id) VALUES (31, 49);
INSERT INTO goals (game_id, player_id) VALUES (31, 49);
INSERT INTO goals (game_id, player_id) VALUES (31, 49);
INSERT INTO goals (game_id, player_id) VALUES (7, 67);
INSERT INTO goals (game_id, player_id) VALUES (7, 67);
INSERT INTO goals (game_id, player_id) VALUES (7, 67);
INSERT INTO goals (game_id, player_id) VALUES (7, 67);
INSERT INTO goals (game_id, player_id) VALUES (7, 57);
INSERT INTO goals (game_id, player_id) VALUES (7, 57);
INSERT INTO goals (game_id, player_id) VALUES (39, 72);
INSERT INTO goals (game_id, player_id) VALUES (39, 72);
INSERT INTO goals (game_id, player_id) VALUES (39, 72);
INSERT INTO goals (game_id, player_id) VALUES (39, 72);
INSERT INTO goals (game_id, player_id) VALUES (39, 57);
INSERT INTO goals (game_id, player_id) VALUES (45, 62);
INSERT INTO goals (game_id, player_id) VALUES (45, 62);
INSERT INTO goals (game_id, player_id) VALUES (45, 62);
INSERT INTO goals (game_id, player_id) VALUES (45, 62);
INSERT INTO goals (game_id, player_id) VALUES (45, 62);
INSERT INTO goals (game_id, player_id) VALUES (45, 62);
INSERT INTO goals (game_id, player_id) VALUES (45, 62);
INSERT INTO goals (game_id, player_id) VALUES (45, 57);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 87);
INSERT INTO goals (game_id, player_id) VALUES (53, 57);
INSERT INTO goals (game_id, player_id) VALUES (32, 82);
INSERT INTO goals (game_id, player_id) VALUES (32, 82);
INSERT INTO goals (game_id, player_id) VALUES (32, 82);
INSERT INTO goals (game_id, player_id) VALUES (32, 82);
INSERT INTO goals (game_id, player_id) VALUES (32, 82);
INSERT INTO goals (game_id, player_id) VALUES (32, 82);
INSERT INTO goals (game_id, player_id) VALUES (32, 57);
INSERT INTO goals (game_id, player_id) VALUES (32, 57);
INSERT INTO goals (game_id, player_id) VALUES (32, 57);
INSERT INTO goals (game_id, player_id) VALUES (48, 72);
INSERT INTO goals (game_id, player_id) VALUES (48, 72);
INSERT INTO goals (game_id, player_id) VALUES (48, 57);
INSERT INTO goals (game_id, player_id) VALUES (48, 57);
INSERT INTO goals (game_id, player_id) VALUES (2, 67);
INSERT INTO goals (game_id, player_id) VALUES (2, 67);
INSERT INTO goals (game_id, player_id) VALUES (2, 67);
INSERT INTO goals (game_id, player_id) VALUES (2, 67);
INSERT INTO goals (game_id, player_id) VALUES (18, 82);
INSERT INTO goals (game_id, player_id) VALUES (18, 82);
INSERT INTO goals (game_id, player_id) VALUES (18, 82);
INSERT INTO goals (game_id, player_id) VALUES (18, 82);
INSERT INTO goals (game_id, player_id) VALUES (18, 82);
INSERT INTO goals (game_id, player_id) VALUES (18, 82);
INSERT INTO goals (game_id, player_id) VALUES (18, 57);
INSERT INTO goals (game_id, player_id) VALUES (18, 57);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 87);
INSERT INTO goals (game_id, player_id) VALUES (14, 57);
INSERT INTO goals (game_id, player_id) VALUES (14, 57);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (5, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 62);
INSERT INTO goals (game_id, player_id) VALUES (52, 72);
INSERT INTO goals (game_id, player_id) VALUES (52, 72);
INSERT INTO goals (game_id, player_id) VALUES (52, 72);
INSERT INTO goals (game_id, player_id) VALUES (21, 82);
INSERT INTO goals (game_id, player_id) VALUES (21, 82);
INSERT INTO goals (game_id, player_id) VALUES (21, 82);
INSERT INTO goals (game_id, player_id) VALUES (21, 82);
INSERT INTO goals (game_id, player_id) VALUES (21, 62);
INSERT INTO goals (game_id, player_id) VALUES (21, 62);
INSERT INTO goals (game_id, player_id) VALUES (21, 62);
INSERT INTO goals (game_id, player_id) VALUES (21, 62);
INSERT INTO goals (game_id, player_id) VALUES (4, 62);
INSERT INTO goals (game_id, player_id) VALUES (4, 62);
INSERT INTO goals (game_id, player_id) VALUES (4, 67);
INSERT INTO goals (game_id, player_id) VALUES (42, 87);
INSERT INTO goals (game_id, player_id) VALUES (42, 87);
INSERT INTO goals (game_id, player_id) VALUES (42, 87);
INSERT INTO goals (game_id, player_id) VALUES (42, 87);
INSERT INTO goals (game_id, player_id) VALUES (35, 62);
INSERT INTO goals (game_id, player_id) VALUES (35, 62);
INSERT INTO goals (game_id, player_id) VALUES (35, 62);
INSERT INTO goals (game_id, player_id) VALUES (35, 62);
INSERT INTO goals (game_id, player_id) VALUES (35, 82);
INSERT INTO goals (game_id, player_id) VALUES (35, 82);
INSERT INTO goals (game_id, player_id) VALUES (25, 62);
INSERT INTO goals (game_id, player_id) VALUES (25, 62);
INSERT INTO goals (game_id, player_id) VALUES (25, 62);
INSERT INTO goals (game_id, player_id) VALUES (25, 62);
INSERT INTO goals (game_id, player_id) VALUES (25, 72);
INSERT INTO goals (game_id, player_id) VALUES (25, 72);
INSERT INTO goals (game_id, player_id) VALUES (49, 87);
INSERT INTO goals (game_id, player_id) VALUES (49, 87);
INSERT INTO goals (game_id, player_id) VALUES (49, 87);
INSERT INTO goals (game_id, player_id) VALUES (49, 87);
INSERT INTO goals (game_id, player_id) VALUES (49, 87);
INSERT INTO goals (game_id, player_id) VALUES (49, 87);
INSERT INTO goals (game_id, player_id) VALUES (49, 62);
INSERT INTO goals (game_id, player_id) VALUES (49, 62);
INSERT INTO goals (game_id, player_id) VALUES (49, 62);
INSERT INTO goals (game_id, player_id) VALUES (30, 62);
INSERT INTO goals (game_id, player_id) VALUES (30, 62);
INSERT INTO goals (game_id, player_id) VALUES (30, 62);
INSERT INTO goals (game_id, player_id) VALUES (30, 62);
INSERT INTO goals (game_id, player_id) VALUES (51, 67);
INSERT INTO goals (game_id, player_id) VALUES (51, 67);
INSERT INTO goals (game_id, player_id) VALUES (51, 67);
INSERT INTO goals (game_id, player_id) VALUES (51, 67);
INSERT INTO goals (game_id, player_id) VALUES (34, 67);
INSERT INTO goals (game_id, player_id) VALUES (34, 67);
INSERT INTO goals (game_id, player_id) VALUES (34, 72);
INSERT INTO goals (game_id, player_id) VALUES (26, 87);
INSERT INTO goals (game_id, player_id) VALUES (26, 87);
INSERT INTO goals (game_id, player_id) VALUES (26, 87);
INSERT INTO goals (game_id, player_id) VALUES (26, 87);
INSERT INTO goals (game_id, player_id) VALUES (26, 67);
INSERT INTO goals (game_id, player_id) VALUES (20, 72);
INSERT INTO goals (game_id, player_id) VALUES (20, 72);
INSERT INTO goals (game_id, player_id) VALUES (20, 72);
INSERT INTO goals (game_id, player_id) VALUES (20, 72);
INSERT INTO goals (game_id, player_id) VALUES (37, 87);
INSERT INTO goals (game_id, player_id) VALUES (37, 87);
INSERT INTO goals (game_id, player_id) VALUES (37, 87);
INSERT INTO goals (game_id, player_id) VALUES (37, 87);
INSERT INTO goals (game_id, player_id) VALUES (37, 67);
INSERT INTO goals (game_id, player_id) VALUES (40, 67);
INSERT INTO goals (game_id, player_id) VALUES (40, 67);
INSERT INTO goals (game_id, player_id) VALUES (40, 67);
INSERT INTO goals (game_id, player_id) VALUES (40, 67);
INSERT INTO goals (game_id, player_id) VALUES (40, 67);
INSERT INTO goals (game_id, player_id) VALUES (40, 67);
INSERT INTO goals (game_id, player_id) VALUES (40, 82);
INSERT INTO goals (game_id, player_id) VALUES (40, 82);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (23, 87);
INSERT INTO goals (game_id, player_id) VALUES (9, 82);
INSERT INTO goals (game_id, player_id) VALUES (9, 82);
INSERT INTO goals (game_id, player_id) VALUES (9, 82);
INSERT INTO goals (game_id, player_id) VALUES (9, 82);
INSERT INTO goals (game_id, player_id) VALUES (9, 82);
INSERT INTO goals (game_id, player_id) VALUES (9, 72);
INSERT INTO goals (game_id, player_id) VALUES (9, 72);
INSERT INTO goals (game_id, player_id) VALUES (9, 72);
INSERT INTO goals (game_id, player_id) VALUES (17, 87);
INSERT INTO goals (game_id, player_id) VALUES (17, 87);
INSERT INTO goals (game_id, player_id) VALUES (17, 87);
INSERT INTO goals (game_id, player_id) VALUES (17, 72);
INSERT INTO goals (game_id, player_id) VALUES (43, 72);
INSERT INTO goals (game_id, player_id) VALUES (43, 72);
INSERT INTO goals (game_id, player_id) VALUES (43, 72);
INSERT INTO goals (game_id, player_id) VALUES (43, 72);
INSERT INTO goals (game_id, player_id) VALUES (43, 72);
INSERT INTO goals (game_id, player_id) VALUES (43, 72);
INSERT INTO goals (game_id, player_id) VALUES (43, 72);
INSERT INTO goals (game_id, player_id) VALUES (28, 87);
INSERT INTO goals (game_id, player_id) VALUES (28, 87);
INSERT INTO goals (game_id, player_id) VALUES (28, 87);
INSERT INTO goals (game_id, player_id) VALUES (28, 87);
INSERT INTO goals (game_id, player_id) VALUES (28, 87);
INSERT INTO goals (game_id, player_id) VALUES (28, 87);
INSERT INTO goals (game_id, player_id) VALUES (28, 82);
INSERT INTO goals (game_id, player_id) VALUES (56, 82);
INSERT INTO goals (game_id, player_id) VALUES (56, 87);
INSERT INTO goals (game_id, player_id) VALUES (56, 87);
INSERT INTO goals (game_id, player_id) VALUES (56, 87);
INSERT INTO goals (game_id, player_id) VALUES (56, 87);
INSERT INTO goals (game_id, player_id) VALUES (56, 87);
INSERT INTO goals (game_id, player_id) VALUES (56, 87);

-- Initial insert: goals for the football league. Mostly Generic.
INSERT INTO goals (game_id, player_id) VALUES (57, 2);
INSERT INTO goals (game_id, player_id) VALUES (57, 2);
INSERT INTO goals (game_id, player_id) VALUES (57, 9);
INSERT INTO goals (game_id, player_id) VALUES (58, 12);
INSERT INTO goals (game_id, player_id) VALUES (59, 3);
INSERT INTO goals (game_id, player_id) VALUES (59, 4);
INSERT INTO goals (game_id, player_id) VALUES (59, 5);
INSERT INTO goals (game_id, player_id) VALUES (59, 5);
INSERT INTO goals (game_id, player_id) VALUES (60, 9);
INSERT INTO goals (game_id, player_id) VALUES (61, 2);
INSERT INTO goals (game_id, player_id) VALUES (63, 4);
INSERT INTO goals (game_id, player_id) VALUES (63, 3);
INSERT INTO goals (game_id, player_id) VALUES (63, 17);
INSERT INTO goals (game_id, player_id) VALUES (64, 7);
INSERT INTO goals (game_id, player_id) VALUES (64, 8);
INSERT INTO goals (game_id, player_id) VALUES (64, 7);
INSERT INTO goals (game_id, player_id) VALUES (64, 13);
INSERT INTO goals (game_id, player_id) VALUES (64, 13);
INSERT INTO goals (game_id, player_id) VALUES (65, 2);
INSERT INTO goals (game_id, player_id) VALUES (65, 8);
INSERT INTO goals (game_id, player_id) VALUES (66, 13);
INSERT INTO goals (game_id, player_id) VALUES (66, 13);
INSERT INTO goals (game_id, player_id) VALUES (66, 13);
INSERT INTO goals (game_id, player_id) VALUES (66, 18);
INSERT INTO goals (game_id, player_id) VALUES (66, 19);