-- Initial inserts: 3 custom leagues, 1 will be in progress.
INSERT INTO leagues (sport, name, league_type_id) VALUES ('Football', 'Fives Mini League','4-DRR-6');
INSERT INTO leagues (sport, name, league_type_id) VALUES ('Rugby', 'Local 7''s league' ,'4-DRR-6');
INSERT INTO leagues (sport, name, league_type_id) VALUES ('Canoe Polo', 'Scottish Div 1 19/20' ,'8-DRR-5-4-6-6-8-8');

-- Initial inserts: teams for all 3 leagues.
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Bayer Neverloosen', 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('When Harry Met Alli', 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Let''s Talk About Cech, Baby', 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('This Could Get Messi', 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Sexton The Beach', 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('The Try Babies', 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('50 Shades Of Jonny Gray', 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Hawaii Try-O', 2, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Glasgow Kayak Club', 3, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Nomads', 3, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Scotia', 3, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Woodmill', 3, 0, 0, 0, 0, 00, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Granite City', 3, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Black Cats', 3, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Dundee Red Helmets', 3, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO teams (name, league_id, games_played, wins, draws, losses, goals_for, goals_against, goal_difference, points) VALUES ('Titans', 3, 0, 0, 0, 0, 0, 0, 0, 0);

-- Initial inserts: players for every team. Generic names for most.
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'Mikey', 24, 'Goalkeeper', 1);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'Ryan', 25, 'Defender', 1);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'Jimmy', 25, 'Defender', 1);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'Valerio', 27, 'Midifielder', 1);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'Andreas', 26, 'Forward', 1);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John A', 25, 'Goalkeeper', 2);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John B', 25, 'Defender', 2);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John C', 25, 'Defender', 2);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John D', 25, 'Midifielder', 2);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John E', 25, 'Forward', 2);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John F', 25, 'Goalkeeper', 3);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John G', 25, 'Defender', 3);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John H', 25, 'Defender', 3);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John I', 25, 'Midifielder', 3);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John J', 25, 'Forward', 3);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John K', 25, 'Goalkeeper', 4);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John L', 25, 'Defender', 4);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John M', 25, 'Defender', 4);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John N', 25, 'Midifielder', 4);
INSERT INTO players (goals_scored, name, age, position, team_id) VALUES (0, 'John O', 25, 'Forward', 4);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 5);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 5);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 5);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 5);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 5);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 5);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 5);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 6);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 6);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 6);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 6);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 6);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 6);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 6);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 7);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 7);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 7);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 7);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 7);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 7);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 7);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 8);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 8);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 8);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 8);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 8);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 8);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JOHN SMITH', 40, 8);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Mikey', 1, 24, 9);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Paul', 2, 31, 9);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Sjoerd', 3, 37, 9);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Callum', 4, 26, 9);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Alan', 5, 32, 9);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Chris', 6, 35, 9);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Arjen', 7, 27, 9);
INSERT INTO players (goals_scored, name, number, age, team_id) VALUES (0, 'Gavin', 8, 29, 9);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 10);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 10);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 10);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 10);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 10);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 11);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 11);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 11);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 11);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 11);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 12);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 12);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 12);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 12);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 12);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 13);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 13);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 13);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 13);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 13);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 14);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 14);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 14);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 14);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 14);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 15);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 15);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 15);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 15);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 15);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 16);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 16);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 16);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 16);
INSERT INTO players (goals_scored, name, age, team_id) VALUES (0, 'JANE DOE', 40, 16);